### PR TITLE
[Encode] Fix a MSDK error when frame info query is enabled

### PR DESCRIPTION
**Pull request by walter-bai**

### CODE REVIEW

**Review by thomasli21801 — APPROVED** [review]

**Comment by dmitryermilov** [comment]
Is it actual for MEdiaSDK as well or VPL one?

**Comment by thomasli21801** [comment]
> Is it actual for MEdiaSDK as well or VPL one?

Hi Dmitry,

I think the fix was intended to be on DG2. So let's probably do VPL CS/OS only.

Thanks,
Thomas

**Comment by AntonGrishin** [comment]
Hi @thomasli21801,
We observe the same issue on cs/os MediaSDK on the ICL/TGL platform
With this fix in MediaSDK, it works correctly.

So probably, we need to port it to legacy RT too.

**Comment by thomasli21801** [comment]
> Hi @thomasli21801,
> We observe the same issue on cs/os MediaSDK on the ICL/TGL platform
> With this fix in MediaSDK, it works correctly.
> 
> So probably, we need to port it to legacy RT too.

Got it. I think Walter prepared for legacy RT as well. Please help accelerate code review.

**Review by vilichev — APPROVED** [review]

**Pull request merged**
